export { TopBanner } from './TopBanner';
export { Navbar } from './Navbar';
export { HeroSection } from './HeroSection';
export { DemoSectionNew as DemoSection } from './DemoSectionNew';
export { DemoSection as DemoSectionOld } from './DemoSection';
export { RevealSection } from './RevealSection';
export { NovaDomainSection } from './NovaDomainSection';
export { ComparisonSection } from './ComparisonSection';
export { PainPointsSection } from './PainPointsSection';
export { CostSection } from './CostSection';
export { HowItWorksSection } from './HowItWorksSection';
export { POSIntegrationSection } from './POSIntegrationSection';
export { FinalCTASection } from './FinalCTASection';
